name: UpdateEPG

on:
  schedule:
    - cron:  '0 12 * * *'
      
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2.1.3
        id: cache-id
        with:
          path: ${{ runner.temp }}/cache
          key: ${{ runner.os }}-cache-v1.0
      
      - uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'
        
      - name: run
        run: |
          python main.py
          tv_sort --by-channel --duplicate-error --output EPG-GRCY.xml EPG-GRCY-tmp.xml
          echo '<!-- generated on '`date -u`' -->' >> EPG-GRCY.xml
          gzip -k EPG-GRCY.xml
          
      - name: Upload EPG
        run: |
          git clone https://.:${{ secrets.BOT_GITHUB_TOKEN }}@github.com/GreekTVApp/greektvapp.github.io target
          rm target/api/EPG-GRCY.xml.gz
          rm target/api/EPG-GRCY.xml
          cp EPG-GRCY.xml.gz target/api/
          cp EPG-GRCY.xml target/api/
          cd target
          git config --global user.name "EPG Bot"
          git config --global user.email "actions@github.com"
          git add api/EPG-GRCY.xml
          git add api/EPG-GRCY.xml.gz
          git commit -m "Update EPG"
          git push https://${{ secrets.BOT_GITHUB_TOKEN }}@github.com/GreekTVApp/greektvapp.github.io.git
