name: MakeEPG

on:
  schedule:
    - cron:  '0 22 * * *'
      
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: install packages
        run: |
          sudo apt-get -q update
          sudo apt-get install python3-bs4
          sudo apt-get install python3-requests
          sudo apt-get install xmltv-util
      - name: run
        run: |
          python main.py
          tv_sort --by-channel --duplicate-error --output EPG-GRCY-tmp.xml EPG-GRCY.xml
          gzip -k EPG-GRCY.xml
        
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./test.xml.gz
          asset_name: EPG-GRCY.xml.gz
          tag: EPG
          overwrite: true
